const HALL_KEY = 'smart-campus-hall';
const CHAT_SOCKET_PATH = '/chat';
const SOCKET_TICKET_TTL_SECONDS = 60;
const DEFAULT_MESSAGE_LIMIT = 30;
const MAX_MESSAGE_LIMIT = 50;
const MAX_TEXT_LENGTH = 2000;

module.exports = {
  HALL_KEY,
  CHAT_SOCKET_PATH,
  SOCKET_TICKET_TTL_SECONDS,
  DEFAULT_MESSAGE_LIMIT,
  MAX_MESSAGE_LIMIT,
  MAX_TEXT_LENGTH,
};
